-- Import et utilisation  des packages Ada nécessaires
with AVR;
with AVR.MCU;
use AVR;

package body LVC.PINS is

   procedure pinMode (port: lvcPins; mode : lvcMode) is
   begin
      case port is
         when D0 => MCU.DDRE_Bits (0) := mode;
         when D1 => MCU.DDRE_Bits (1) := mode;
         when D2 => MCU.DDRE_Bits (4) := mode;
         when D3 => MCU.DDRE_Bits (5) := mode;
         when D4 => MCU.DDRG_Bits (5) := mode;
         when D5 => MCU.DDRE_Bits (3) := mode;
         when D6 => MCU.DDRH_Bits (3) := mode;
         when D7 => MCU.DDRH_Bits (4) := mode;
         when D8 => MCU.DDRH_Bits (5) := mode;
         when D9 => MCU.DDRH_Bits (6) := mode;
         when D10 => MCU.DDRB_Bits (4) := mode;
         when D11 => MCU.DDRB_Bits (5) := mode;
         when D12 => MCU.DDRB_Bits (6) := mode;
         when D13 => MCU.DDRB_Bits (7) := mode;
         when D14 => MCU.DDRJ_Bits (1) := mode;
         when D15 => MCU.DDRJ_Bits (0) := mode;
         when D16 => MCU.DDRH_Bits (1) := mode;
         when D17 => MCU.DDRH_Bits (0) := mode;
         when D18 => MCU.DDRD_Bits (3) := mode;
         when D19 => MCU.DDRD_Bits (2) := mode;
         when D20 => MCU.DDRD_Bits (1) := mode;
         when D21 => MCU.DDRD_Bits (0) := mode;
         when D22 => MCU.DDRA_Bits (0) := mode;
         when D23 => MCU.DDRA_Bits (1) := mode;
         when D24 => MCU.DDRA_Bits (2) := mode;
         when D25 => MCU.DDRA_Bits (3) := mode;
         when D26 => MCU.DDRA_Bits (4) := mode;
         when D27 => MCU.DDRA_Bits (5) := mode;
         when D28 => MCU.DDRA_Bits (6) := mode;
         when D29 => MCU.DDRA_Bits (7) := mode;
         when D30 => MCU.DDRC_Bits (7) := mode;
         when D31 => MCU.DDRC_Bits (6) := mode;
         when D32 => MCU.DDRC_Bits (5) := mode;
         when D33 => MCU.DDRC_Bits (4) := mode;
         when D34 => MCU.DDRC_Bits (3) := mode;
         when D35 => MCU.DDRC_Bits (2) := mode;
         when D36 => MCU.DDRC_Bits (1) := mode;
         when D37 => MCU.DDRC_Bits (0) := mode;
         when D38 => MCU.DDRD_Bits (7) := mode;
         when D39 => MCU.DDRG_Bits (2) := mode;
         when D40 => MCU.DDRG_Bits (1) := mode;
         when D41 => MCU.DDRG_Bits (0) := mode;
         when D42 => MCU.DDRL_Bits (7) := mode;
         when D43 => MCU.DDRL_Bits (6) := mode;
         when D44 => MCU.DDRL_Bits (5) := mode;
         when D45 => MCU.DDRL_Bits (4) := mode;
         when D46 => MCU.DDRL_Bits (3) := mode;
         when D47 => MCU.DDRL_Bits (2) := mode;
         when D48 => MCU.DDRL_Bits (1) := mode;
         when D49 => MCU.DDRL_Bits (0) := mode;
         when D50 => MCU.DDRB_Bits (3) := mode;
         when D51 => MCU.DDRB_Bits (2) := mode;
         when D52 => MCU.DDRB_Bits (1) := mode;
         when D53 => MCU.DDRB_Bits (0) := mode;
         when A0 => MCU.DDRF_Bits (0) := mode;
         when A1 => MCU.DDRF_Bits (1) := mode;
         when A2 => MCU.DDRF_Bits (2) := mode;
         when A3 => MCU.DDRF_Bits (3) := mode;
         when A4 => MCU.DDRF_Bits (4) := mode;
         when A5 => MCU.DDRF_Bits (5) := mode;
         when A6 => MCU.DDRF_Bits (6) := mode;
         when A7 => MCU.DDRF_Bits (7) := mode;
         when A8 => MCU.DDRK_Bits (0) := mode;
         when A9 => MCU.DDRK_Bits (1) := mode;
         when A10 => MCU.DDRK_Bits (2) := mode;
         when A11 => MCU.DDRK_Bits (3) := mode;
         when A12 => MCU.DDRK_Bits (4) := mode;
         when A13 => MCU.DDRK_Bits (5) := mode;
         when A14 => MCU.DDRK_Bits (6) := mode;
         when A15 => MCU.DDRK_Bits (7) := mode;
         when others => null;
      end case;
   end pinMode;


   procedure digitalWrite(port : lvcPins; level : lvcLevel) is
   begin
      case port is
         when D0 => MCU.PORTE_Bits (0) := level;
         when D1 => MCU.PORTE_Bits (1) := level;
         when D2 => MCU.PORTE_Bits (4) := level;
         when D3 => MCU.PORTE_Bits (5) := level;
         when D4 => MCU.PORTG_Bits (5) := level;
         when D5 => MCU.PORTE_Bits (3) := level;
         when D6 => MCU.PORTH_Bits (3) := level;
         when D7 => MCU.PORTH_Bits (4) := level;
         when D8 => MCU.PORTH_Bits (5) := level;
         when D9 => MCU.PORTH_Bits (6) := level;
         when D10 => MCU.PORTB_Bits (4) := level;
         when D11 => MCU.PORTB_Bits (5) := level;
         when D12 => MCU.PORTB_Bits (6) := level;
         when D13 => MCU.PORTB_Bits (7) := level;
         when D14 => MCU.PORTJ_Bits (1) := level;
         when D15 => MCU.PORTJ_Bits (0) := level;
         when D16 => MCU.PORTH_Bits (1) := level;
         when D17 => MCU.PORTH_Bits (0) := level;
         when D18 => MCU.PORTD_Bits (3) := level;
         when D19 => MCU.PORTD_Bits (2) := level;
         when D20 => MCU.PORTD_Bits (1) := level;
         when D21 => MCU.PORTD_Bits (0) := level;
         when D22 => MCU.PORTA_Bits (0) := level;
         when D23 => MCU.PORTA_Bits (1) := level;
         when D24 => MCU.PORTA_Bits (2) := level;
         when D25 => MCU.PORTA_Bits (3) := level;
         when D26 => MCU.PORTA_Bits (4) := level;
         when D27 => MCU.PORTA_Bits (5) := level;
         when D28 => MCU.PORTA_Bits (6) := level;
         when D29 => MCU.PORTA_Bits (7) := level;
         when D30 => MCU.PORTC_Bits (7) := level;
         when D31 => MCU.PORTC_Bits (6) := level;
         when D32 => MCU.PORTC_Bits (5) := level;
         when D33 => MCU.PORTC_Bits (4) := level;
         when D34 => MCU.PORTC_Bits (3) := level;
         when D35 => MCU.PORTC_Bits (2) := level;
         when D36 => MCU.PORTC_Bits (1) := level;
         when D37 => MCU.PORTC_Bits (0) := level;
         when D38 => MCU.PORTD_Bits (7) := level;
         when D39 => MCU.PORTG_Bits (2) := level;
         when D40 => MCU.PORTG_Bits (1) := level;
         when D41 => MCU.PORTG_Bits (0) := level;
         when D42 => MCU.PORTL_Bits (7) := level;
         when D43 => MCU.PORTL_Bits (6) := level;
         when D44 => MCU.PORTL_Bits (5) := level;
         when D45 => MCU.PORTL_Bits (4) := level;
         when D46 => MCU.PORTL_Bits (3) := level;
         when D47 => MCU.PORTL_Bits (2) := level;
         when D48 => MCU.PORTL_Bits (1) := level;
         when D49 => MCU.PORTL_Bits (0) := level;
         when D50 => MCU.PORTB_Bits (3) := level;
         when D51 => MCU.PORTB_Bits (2) := level;
         when D52 => MCU.PORTB_Bits (1) := level;
         when D53 => MCU.PORTB_Bits (0) := level;
         when A0 => MCU.PORTF_Bits (0) := level;
         when A1 => MCU.PORTF_Bits (1) := level;
         when A2 => MCU.PORTF_Bits (2) := level;
         when A3 => MCU.PORTF_Bits (3) := level;
         when A4 => MCU.PORTF_Bits (4) := level;
         when A5 => MCU.PORTF_Bits (5) := level;
         when A6 => MCU.PORTF_Bits (6) := level;
         when A7 => MCU.PORTF_Bits (7) := level;
         when A8 => MCU.PORTK_Bits (0) := level;
         when A9 => MCU.PORTK_Bits (1) := level;
         when A10 => MCU.PORTK_Bits (2) := level;
         when A11 => MCU.PORTK_Bits (3) := level;
         when A12 => MCU.PORTK_Bits (4) := level;
         when A13 => MCU.PORTK_Bits (5) := level;
         when A14 => MCU.PORTK_Bits (6) := level;
         when A15 => MCU.PORTK_Bits (7) := level;
         when others => null;
      end case;
   end digitalWrite;

end LVC.PINS;

